import logging
import re
from fastapi import APIRouter, HTTPException, Depends, status
from pydantic import BaseModel, field_validator
from auth import get_current_user
from database import conversations_col, notifications_col
from services.langgraph_service import app_graph
from services.profile_service import get_user_profile, update_user_profile
from services.memory_service import get_all_sessions
from bson import ObjectId

router = APIRouter()
logger = logging.getLogger(__name__)

def sanitize_input(text: str) -> str:
    dangerous_patterns = [r'\[EXTRACT:', r'\[SYSTEM:', r'\[ADMIN:', r'\[INSTRUCTION:', r'<script', r'javascript:', r'onerror=', r'onclick=']
    for pattern in dangerous_patterns:
        text = re.sub(pattern, '', text, flags=re.IGNORECASE)
    return ' '.join(text.split())[:2000].strip()

class ChatRequest(BaseModel):
    user_input: str
    session_id: str = "default"

    @field_validator("user_input")
    @classmethod
    def must_not_be_empty(cls, v: str) -> str:
        if not v.strip(): raise ValueError("user_input cannot be empty")
        return v.strip()


class ProfileUpdateRequest(BaseModel):
    key: str
    value: str

    @field_validator("key")
    @classmethod
    def validate_key(cls, value: str) -> str:
        cleaned = value.strip().lower()
        if not cleaned:
            raise ValueError("key cannot be empty")
        if len(cleaned) > 100:
            raise ValueError("key is too long")
        return cleaned

    @field_validator("value")
    @classmethod
    def validate_value(cls, value: str) -> str:
        cleaned = value.strip()
        if not cleaned:
            raise ValueError("value cannot be empty")
        return cleaned[:500]

@router.post("/chat")
async def chat(request: ChatRequest, current_user: dict = Depends(get_current_user)):
    try:
        sanitized_input = sanitize_input(request.user_input)
        result = app_graph.invoke({
            "input": sanitized_input,
            "session_id": request.session_id,
            "user_id": current_user["id"]
        })
        output = result.get("output") if result else None
        if not output:
            raise HTTPException(
                status_code=status.HTTP_502_BAD_GATEWAY,
                detail="No response generated by chat engine",
            )
        return {"response": output}
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"[ROUTE] Chat failed: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Chat request failed",
        )

@router.get("/profile")
async def get_profile(current_user: dict = Depends(get_current_user)):
    return get_user_profile(current_user["id"])

@router.post("/profile")
async def update_profile(update: ProfileUpdateRequest, current_user: dict = Depends(get_current_user)):
    update_user_profile(current_user["id"], update.key, update.value)
    return {"status": "success"}

@router.get("/sessions")
async def get_sessions_route(current_user: dict = Depends(get_current_user), limit: int = 50, offset: int = 0):
    sessions = get_all_sessions(current_user["id"])
    return sessions[offset:offset+limit]

@router.get("/sessions/{session_id}")
async def get_session_history(session_id: str, current_user: dict = Depends(get_current_user)):
    docs = conversations_col.find({"user_id": current_user["id"], "session_id": session_id}).sort("created_at", 1)
    history = []
    for c in docs:
        history.append({"role": "user", "text": c["user_input"], "created_at": str(c["created_at"])})
        history.append({"role": "bot", "text": c["bot_response"], "created_at": str(c["created_at"])})
    return history

@router.delete("/sessions/{session_id}")
async def delete_session_route(session_id: str, current_user: dict = Depends(get_current_user)):
    conversations_col.delete_many({"user_id": current_user["id"], "session_id": session_id})
    return {"status": "success"}

@router.get("/notifications")
async def get_notifications(current_user: dict = Depends(get_current_user)):
    notifs = notifications_col.find({"user_id": current_user["id"], "is_read": False})
    return [{"id": str(n["_id"]), "message": n["message"], "created_at": str(n["created_at"])} for n in notifs]

@router.post("/notifications/read/{notif_id}")
async def mark_notification_read(notif_id: str, current_user: dict = Depends(get_current_user)):
    if not ObjectId.is_valid(notif_id):
        raise HTTPException(status_code=400, detail="Invalid notification id")
    result = notifications_col.update_one({"_id": ObjectId(notif_id), "user_id": current_user["id"]}, {"$set": {"is_read": True}})
    if result.matched_count == 0:
        raise HTTPException(status_code=404, detail="Notification not found")
    return {"status": "success"}

@router.delete("/notifications/{notif_id}")
async def delete_notification(notif_id: str, current_user: dict = Depends(get_current_user)):
    if not ObjectId.is_valid(notif_id):
        raise HTTPException(status_code=400, detail="Invalid notification id")
    result = notifications_col.delete_one({"_id": ObjectId(notif_id), "user_id": current_user["id"]})
    if result.deleted_count == 0:
        raise HTTPException(status_code=404, detail="Notification not found")
    return {"status": "success"}
